---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Create container
      community.general.lxd_container:
        name: test
        state: started
        ignore_volatile_options: true
        wait_for_ipv4_addresses: true
        profiles:
          - default
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: alpine/edge
